#!/bin/sh 

mkdir -p ./dist/

export VER=`rg --no-line-number --trim --replace '$1' 'Version = "([^\s]*)"' ./main.go`

export GOOS='linux' GOARCH='amd64'
echo "building ${GOOS} ${GOARCH} ${VER}"
go build -o "./out/$GOOS/$GOARCH/"
tar -czvf "./dist/jx_${GOOS}_${GOARCH}-${VER}.tar.gz" "./out/$GOOS/$GOARCH/jx"

export GOOS='linux' GOARCH='386'
echo "building ${GOOS} ${GOARCH} ${VER}"
go build -o "./out/$GOOS/$GOARCH/"
tar -czvf "./dist/jx_${GOOS}_${GOARCH}-${VER}.tar.gz" "./out/$GOOS/$GOARCH/jx"

export GOOS='darwin' GOARCH='amd64'
echo "building ${GOOS} ${GOARCH} ${VER}"
go build -o "./out/$GOOS/$GOARCH/"
tar -czvf "./dist/jx_${GOOS}_${GOARCH}-${VER}.tar.gz" "./out/$GOOS/$GOARCH/jx"

export GOOS='darwin' GOARCH='arm64' 
echo "building ${GOOS} ${GOARCH} ${VER}"
go build -o "./out/$GOOS/$GOARCH/"
tar -czvf "./dist/jx_${GOOS}_${GOARCH}-${VER}.tar.gz" "./out/$GOOS/$GOARCH/jx"

export GOOS='windows' GOARCH='amd64' VER='0.0.6'
echo "building ${GOOS} ${GOARCH} ${VER}"
go build -o "./out/$GOOS/$GOARCH/"
zip "./dist/jx_${GOOS}_${GOARCH}-${VER}.zip" "./out/$GOOS/$GOARCH/jx.exe"

export GOOS='windows' GOARCH='386'
echo "building ${GOOS} ${GOARCH} ${VER}"
go build -o "./out/$GOOS/$GOARCH/"
zip "./dist/jx_${GOOS}_${GOARCH}-${VER}.zip" "./out/$GOOS/$GOARCH/jx.exe"

